config/routes.rb
Events::Application.routes.draw do
  root "events#index"
  
  get "events/archived" => "events#archived", as: "archived_events"

  resources :events do
    resources :registrations
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

  validates :name, :location, presence: true
  validates :description, length: { minimum: 25 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :capacity, numericality: { only_interger: true, 
                                       greater_than: 0 }
  validates :image_file_name, allow_blank: true, format: {
    with: /\w+\.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }

  has_many :registrations, dependent: :destroy

  def self.upcoming
    where("starts_at >= ?", Time.now).order("starts_at")   
  end

  def self.archived
    where("starts_at <= ?", Time.now).order("starts_at")   
  end

  def free?
    price.blank? || price.zero?
  end
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.upcoming
  end

  def archived
    @events = Event.archived
  end

  def show
    @event = Event.find(params[:id])    
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "Event successfully updated!"
    else
      render :new
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params) 
    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url, notice: "An event has been deleted."

  end

private

 def event_params
   event_params = params
    .require(:event)
    .permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)
 end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def index
    @event = Event.find(params[:event_id])
    @registrations = @event.registrations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def format_price(event)
    if event.free?
      content_tag(:strong, 'Free')
    else
      number_to_currency(event.price)
    end
  end

  def image_for(event)
    if event.image_file_name.blank?
      image_tag 'awesome-unicorn.png'
    else
      image_tag event.image_file_name
    end
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/events/_errors.html.haml
- if object.errors.any?
  #errors
    %p 
      %strong Oops!
      You messed it all up. Here, fix this junk.
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/events/_events_list.html.haml
- @events.each do |event|
  .event
    %h2= link_to event.name, event
    = image_for(event)
    %p= truncate(event.description, length: 35, separator: '')
    %ul
      %li
        %strong When:
        = event.starts_at
      %li
        %strong Where:
        = event.location
      %li
        %strong Price:
        = format_price(event)

app/views/events/_form.html.haml
= form_for @event do |f|
  = render "errors", object: @event
  %ol
    %li
      = f.label :name
      = f.text_field :name, placeholder: "Name", autofocus: true
    %li
      = f.label :image_file_name
      = f.text_field :image_file_name, size: 30, placeholder: "GIF, JPG, or PNG file name"
    %li
      = f.label :capacity
      = f.text_field :capacity, placeholder: "Capacity"
    %li
      = f.label :description
      = f.text_area :description, placeholder: "Description"
    %li
      = f.label :location
      = f.text_field :location, placeholder: "Location"
    %li
      = f.label :price
      = f.number_field :price, placeholder: "Price"
    %li
      = f.label :starts_at
      = f.date_field :starts_at, placeholder: "Date of Event"
  = f.submit

app/views/events/archived.html.haml
%h1= pluralize(@events.size, 'Archived Event')
= link_to "Upcoming Event", events_path
%article
= render "events_list"

app/views/events/edit.html.haml
%h1 Editing Event: #{@event.name} 
= render partial: "form"

app/views/events/index.html.haml
%h1= pluralize(@events.size, 'Upcoming Event')
%ul
  %li= link_to "Add Event", new_event_path
  %li= link_to "Archived Events", archived_events_path
%article
= render "events_list"

app/views/events/new.html.haml
%h1 Add New Event
= render partial: "form"
= link_to "Back to Events", events_url

app/views/events/show.html.haml
%article
  %h1= @event.name
  = image_for(@event)
  %p= @event.description
  %ul
    %li
      %strong When:
      = @event.starts_at
    %li
      %strong Where:
      = @event.location
    %li
      %strong Price:
      = format_price(@event)
  %p
    %strong= pluralize(@event.capacity, "spot") 
  = link_to "View Registrations", event_registrations_path(@event)
  %ul.links
    %li.admin.edit
      = link_to "Edit", edit_event_path
    %li
      = link_to "Back to Events", events_path
    %li.admin.delete
      = link_to "Delete", event_path(@event), 
                method: :delete, 
                data: {confirm: "ORly?"}

app/views/layouts/_messages.html.haml
= flash[:notice]

app/views/layouts/application.html.haml
!!! 5
/[if lt IE 7] <html class="lt-ie10 lt-ie9 lt-ie8 lt-ie7">
/[if IE 7] <html class="lt-ie10 lt-ie9 lt-ie8">
/[if IE 8] <html class="lt-ie10 lt-ie9">
/[if IE 9] <html class="lt-ie10">
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
%head
  %meta{ charset: "utf-8" } 
  %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
  %title Events

  = stylesheet_link_tag "application",
    media: "all",
    "data-turbolinks-track" => true
  = javascript_include_tag "application",
    "data-turbolinks-track" => true
  = yield( :javascript_includes)
  = csrf_meta_tags
  = yield( :head)

%header#header

%body
  = render "layouts/messages"
  = yield

%footer#footer